build:
  environment:
    python: 3.6.3
  tests:
    override:
      - pylint-run --rcfile=.pylint.ini
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - "*/tests/*"
